Repository team-mozu/mozu-FE, pull requests merged in 2025-01, with the labels that each got.

#3 feat : Header 퍼블리싱 및 packages/ui emotion 설치
  packages/ui/Header.tsx
  packages/ui/assets/common/LogoWithText.tsx
  packages/ui/assets/common/index.ts
  packages/ui/assets/index.ts
  packages/ui/package.json
  yarn.lock
Labels: 🧑‍💻 feat

#5 feat : Button 퍼블리싱
  packages/ui/Button.tsx
  packages/ui/assets/icon/Del.tsx
  packages/ui/assets/icon/Edit.tsx
  packages/ui/assets/icon/Plus.tsx
  packages/ui/assets/icon/Save.tsx
  packages/ui/assets/icon/Start.tsx
  packages/ui/assets/icon/index.ts
  packages/ui/assets/index.ts
Labels: 🧑‍💻 feat

#7 feat : ClassPost 퍼블리싱 및 color.ts의 색상 추가
  packages/design-token/src/theme/color.ts
  packages/ui/ClassPost.tsx
  packages/ui/assets/icon/Del.tsx
  packages/ui/assets/icon/Edit.tsx
  packages/ui/assets/icon/Plus.tsx
  packages/ui/assets/icon/Save.tsx
  packages/ui/assets/icon/Star.tsx
  packages/ui/assets/icon/Start.tsx
  packages/ui/assets/icon/index.ts
  packages/ui/index.ts
Labels: 🧑‍💻 feat

#9 merge : develop → main: 최신 작업 동기화
  packages/design-token/src/theme/color.ts
  packages/ui/Button.tsx
  packages/ui/ClassPost.tsx
  packages/ui/Header.tsx
  packages/ui/assets/common/LogoWithText.tsx
  packages/ui/assets/common/index.ts
  packages/ui/assets/icon/Del.tsx
  packages/ui/assets/icon/Edit.tsx
  packages/ui/assets/icon/Plus.tsx
  packages/ui/assets/icon/Save.tsx
  packages/ui/assets/icon/Star.tsx
  packages/ui/assets/icon/Start.tsx
  packages/ui/assets/icon/index.ts
  packages/ui/assets/index.ts
  packages/ui/index.ts
  packages/ui/package.json
  yarn.lock
Labels: ⚙️ setting

#15 feat : SideBar 퍼블리싱
  .yarn/releases/yarn-4.6.0.cjs
  .yarnrc.yml
  package-lock.json
  package.json
  packages/ui/NavBtn.tsx
  packages/ui/SideBar.tsx
  packages/ui/assets/icon/ArticleIcon.tsx
  packages/ui/assets/icon/ClassIcon.tsx
  packages/ui/assets/icon/ManagerLogo.tsx
  packages/ui/assets/icon/StockIcon.tsx
  packages/ui/assets/icon/index.ts
  packages/ui/index.ts
  packages/ui/package.json
  yarn.lock
Labels: 🧑‍💻 feat

#19 feat : InvestmentMetrics 퍼블리싱
  packages/ui/InvestmentMetrics.tsx
Labels: 🧑‍💻 feat

#22 feat : eslint, prettier config 추가 및 components test 동기화
  .eslintignore
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/bug-report-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .vscode/settings.json
  .yarn/sdks/eslint/lib/types/index.d.ts
  .yarn/sdks/eslint/lib/types/rules/index.d.ts
  .yarn/sdks/eslint/lib/types/universal.d.ts
  .yarn/sdks/eslint/lib/types/use-at-your-own-risk.d.ts
  .yarn/sdks/eslint/lib/universal.js
  .yarn/sdks/eslint/package.json
  .yarn/sdks/typescript/package.json
  package.json
  packages/admin/.eslintrc.cjs
  packages/admin/README.md
  packages/admin/eslint.config.js
  packages/admin/index.html
  packages/admin/package.json
  packages/admin/src/App.tsx
  packages/admin/src/index.tsx
  packages/admin/src/router.tsx
  packages/admin/src/test.tsx
  packages/admin/tsconfig.json
  packages/admin/vite.config.ts
  packages/design-token/index.ts
  packages/design-token/src/index.ts
  packages/design-token/src/theme/index.ts
  packages/eslint-config/README.md
  packages/eslint-config/index.js
  packages/eslint-config/mixins/react.js
  packages/eslint-config/package.json
  packages/eslint-config/patch.js
  packages/prettier-config/README.md
  packages/prettier-config/index.js
  packages/prettier-config/package.json
  packages/ui/package.json
  packages/ui/src/Button.tsx
  packages/ui/src/ClassPost.tsx
  packages/ui/src/Header.tsx
  packages/ui/src/NavBtn.tsx
  packages/ui/src/SideBar.tsx
  packages/ui/src/assets/common/LogoWithText.tsx
  packages/ui/src/assets/icon/ArticleIcon.tsx
  packages/ui/src/assets/icon/ClassIcon.tsx
  packages/ui/src/assets/icon/Del.tsx
  packages/ui/src/assets/icon/Edit.tsx
  packages/ui/src/assets/icon/ManagerLogo.tsx
  packages/ui/src/assets/icon/Plus.tsx
  packages/ui/src/assets/icon/Save.tsx
  packages/ui/src/assets/icon/Star.tsx
  packages/ui/src/assets/icon/Start.tsx
  packages/ui/src/assets/icon/StockIcon.tsx
  packages/ui/tsconfig.json
  yarn.lock
Labels: 🧑‍💻 feat

#24 fix : select button 버그 fix
  packages/admin/src/test.tsx
  packages/design-token/src/theme/font.ts
  packages/design-token/tsconfig.json
  packages/ui/src/Select.tsx
  packages/ui/src/assets/icon/ChevronDown.tsx
Labels: 👾 BUG

#21 feat : Accounts 퍼블리싱
  packages/ui/Accounts.tsx
Labels: 🧑‍💻 feat

#25 feat: Invest Table 퍼블리싱
  packages/ui/src/CheckBox.tsx
  packages/ui/src/InvestTable.tsx
  packages/ui/src/assets/icon/Check.tsx
  packages/ui/src/assets/icon/index.ts
  packages/ui/src/index.ts
  yarn.lock
Labels: 🧑‍💻 feat

#29 feat : AddInvestItemModal 퍼블리싱
  .DS_Store
  packages/design-token/src/theme/font.ts
  packages/ui/SearchInput.tsx
  packages/ui/src/AddInvestItemModal.tsx
  packages/ui/src/Button.tsx
  packages/ui/src/Checkbox.tsx
  packages/ui/src/Item.tsx
  packages/ui/src/assets/icon/Check.tsx
  packages/ui/src/assets/icon/index.ts
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#34 feat : input 퍼블리싱
  packages/admin/src/test.tsx
  packages/ui/src/Input.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#41 feat : AddInvestItemModal 페이지 전체 선택 기능 구현
  packages/ui/src/AddInvestItemModal.tsx
  packages/ui/src/Item.tsx
Labels: 🧑‍💻 feat

#43 feat : Modal Background 클릭 시 닫기 기능
  packages/ui/src/AddInvestItemModal.tsx
Labels: 🧑‍💻 feat

#38 feat : textarea 퍼블리싱
  packages/ui/src/TextArea.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#40 feat : DeleteModal 퍼블리싱
  packages/design-token/src/theme/color.ts
  packages/ui/src/DeleteModal.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#44 feat : header 색상 수정
  packages/ui/src/Header.tsx
Labels: 🧑‍💻 feat

#45 feat : ClassPost 폰트 미적용 수정
  packages/ui/src/ClassPost.tsx
Labels: 🧑‍💻 feat

#47 feat : select error 컴포넌트 퍼블리싱
  packages/ui/src/SelectError.tsx
  packages/ui/src/assets/icon/Info.tsx
  packages/ui/src/assets/icon/index.ts
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#35 기사 목록 표 퍼블리싱 & 표 컴포넌트 재활용
  packages/ui/src/InvestTable.tsx
  packages/ui/src/Tables.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#42 feat: 기사 추가 모달 구현
  packages/ui/src/AddArticleItemModal.tsx
  packages/ui/src/AddInvestItemModal.tsx
  packages/ui/src/ArticleItem.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#49 feat : stock-detail 페이지 퍼블리싱
  packages/admin/src/pages/StockManagementPage.tsx
  packages/admin/src/router.tsx
  packages/ui/src/StockManagementDetail.tsx
Labels: 🧑‍💻 feat

#52 feat : ClassManagement 퍼블리싱
  packages/admin/src/pages/ClassManagement.tsx
  packages/admin/src/pages/index.ts
  packages/admin/src/router.tsx
  packages/ui/src/Button.tsx
  packages/ui/src/ClassPost.tsx
  packages/ui/src/NavBtn.tsx
  packages/ui/src/PostTitle.tsx
  packages/ui/src/Title.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#54 feat : Delete Modal 구현
  packages/ui/src/DeleteModal.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#56 feat : ArticleManagementAdd 퍼블리싱
  .DS_Store
  packages/admin/src/pages/ArticleManagementAdd.tsx
  packages/admin/src/pages/ClassManagement.tsx
  packages/admin/src/pages/index.ts
  packages/admin/src/router.tsx
  packages/ui/src/Button.tsx
  packages/ui/src/EditDiv.tsx
  packages/ui/src/ImgContainer.tsx
  packages/ui/src/Input.tsx
  packages/ui/src/TextArea.tsx
  packages/ui/src/assets/icon/Imglogo.tsx
  packages/ui/src/assets/icon/index.ts
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#57 feat : ArticleManagementAdd 페이지 width 수정
  packages/admin/src/pages/ArticleManagementAdd.tsx
  packages/admin/src/router.tsx
Labels: 🧑‍💻 feat

#59 feat : StockManagementAddPage 퍼블리싱
  packages/admin/src/pages/StockManagementAddPage.tsx
  packages/ui/src/Button.tsx
  packages/ui/src/Input.tsx
  packages/ui/src/LogoUploader.tsx
  packages/ui/src/assets/icon/Imglogo.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#65 feat : ArticleManagementEdit 퍼블리싱
  packages/admin/src/pages/ArticleManagementEdit.tsx
  packages/admin/src/pages/index.ts
  packages/admin/src/router.tsx
  packages/ui/src/ImgContainer.tsx
  packages/ui/src/Input.tsx
  packages/ui/src/TextArea.tsx
  packages/ui/src/assets/icon/Imglogo.tsx
Labels: 🧑‍💻 feat

#68 feat: 수업 생성 페이지 제작 (모달 미구현)
  packages/admin/src/pages/CreateClass.tsx
  packages/admin/src/router.tsx
  packages/ui/src/AddArticleItemModal.tsx
  packages/ui/src/Tables.tsx
Labels: 🧑‍💻 feat

#63 feat : article management 퍼블리싱
  packages/admin/src/pages/ArticleManagementAdd.tsx
  packages/admin/src/pages/ArticleManagementPage.tsx
  packages/admin/src/pages/index.ts
  packages/admin/src/router.tsx
  packages/ui/src/ArticleDiv.tsx
  packages/ui/src/ArticleMainData.tsx
  packages/ui/src/ArticleManagementDetail.tsx
  packages/ui/src/ArticleSearchSideBar.tsx
  packages/ui/src/StockSearchSideBar.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#72 feat: 수업 생성 페이지 모달 기능 추가
  packages/admin/src/pages/CreateClass.tsx
  packages/ui/src/AddArticleItemModal.tsx
  packages/ui/src/AddInvestItemModal.tsx
  packages/ui/src/Tables.tsx
Labels: 🧑‍💻 feat

#67 feat : InvestmentPreparation 퍼블리싱
  packages/admin/src/pages/InvestmentPreparation.tsx
  packages/admin/src/router.tsx
  packages/ui/src/Button.tsx
  packages/ui/src/ParticipationContainer.tsx
  packages/ui/src/TeamContainer.tsx
  packages/ui/src/WarningMsg.tsx
  packages/ui/src/assets/icon/Cancel.tsx
  packages/ui/src/assets/icon/Dot.tsx
  packages/ui/src/assets/icon/Warning .tsx
  packages/ui/src/assets/icon/index.ts
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#74 feat: 수업 수정 페이지 퍼블리싱
  packages/admin/src/pages/ClassCreate.tsx
  packages/admin/src/pages/ClassEdit.tsx
  packages/admin/src/pages/CreateClass.tsx
  packages/admin/src/pages/index.ts
  packages/admin/src/router.tsx
  packages/ui/src/Tables.tsx
Labels: 🧑‍💻 feat

#76 feat : router 연동 및 signin 페이지 퍼블리싱
  packages/admin/src/pages/ArticleManagementAddPage.tsx
  packages/admin/src/pages/ArticleManagementEditPage.tsx
  packages/admin/src/pages/ClassCreate.tsx
  packages/admin/src/pages/ClassEdit.tsx
  packages/admin/src/pages/ClassEnvironment.tsx
  packages/admin/src/pages/ClassManagement.tsx
  packages/admin/src/pages/InvestmentPreparation.tsx
  packages/admin/src/pages/SignInPage.tsx
  packages/admin/src/pages/index.ts
  packages/admin/src/router.tsx
  packages/ui/src/AddButton.tsx
  packages/ui/src/ArticleSearchSideBar.tsx
  packages/ui/src/ClassPost.tsx
  packages/ui/src/EditDiv.tsx
  packages/ui/src/Header.tsx
  packages/ui/src/Input.tsx
  packages/ui/src/NavBtn.tsx
  packages/ui/src/Select.tsx
  packages/ui/src/SideBar.tsx
  packages/ui/src/StockSearchSideBar.tsx
  packages/ui/src/TextArea.tsx
  packages/ui/src/assets/icon/Eye.tsx
  packages/ui/src/assets/icon/EyeOff.tsx
  packages/ui/src/assets/icon/index.ts
Labels: 🧑‍💻 feat, ♻️ refactor

#80 테이블 크기 수정
  packages/admin/src/pages/ClassEnvironment.tsx
  packages/ui/src/Tables.tsx
Labels: 👾 BUG

#78 feat : ArticleInfo 퍼블리싱
  packages/ui/src/ArticleInfo.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#86 팀 거래 현황 테이블 퍼블리싱
  packages/ui/src/TeamInfoTable.tsx
  packages/ui/src/TeamInvestStatusTable.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#84 투자 정보 테이블 개발
  packages/ui/src/InvestInfoTable.tsx
  packages/ui/src/Tables.tsx
  packages/ui/src/TeamInfoTable.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#88 feat : monitoring-modal 퍼블리싱
  packages/admin/src/pages/ClassMonitoringPage.tsx
  packages/ui/src/ArticleInfoModal.tsx
  packages/ui/src/ClassInfoModal.tsx
  packages/ui/src/TeamCurrentModal.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#89 feat : header 학생 퍼블리싱
  packages/admin/src/layout/AppLayout.tsx
  packages/ui/src/Header.tsx
Labels: 🧑‍💻 feat

#92 feat : NewsPost 퍼블리싱
  packages/ui/src/NewsPost.tsx
  packages/ui/src/assets/common/index.ts
  packages/ui/src/assets/common/noImg.svg
  packages/ui/src/assets/icon/NoImgIcon.tsx
  packages/ui/src/assets/icon/index.ts
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#94 feat : Ranking Div 퍼블리싱
  packages/student/src/layout/AppLayout.tsx
  packages/ui/src/RankingDiv.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#97 feat : Sidebar 퍼블리싱
  packages/ui/src/HistorySidebar.tsx
  packages/ui/src/ItemSidebar.tsx
  packages/ui/src/assets/icon/NoImgIcon.tsx
  packages/ui/src/assets/icon/index.ts
  packages/ui/src/assets/icon/noImgIcon.svg
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#99 feat : ExitBtn 퍼블리싱
  packages/ui/src/ExitBtn.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#105 feat : rank modal 퍼블리싱
  packages/student/src/components/rank/RankModal.tsx
  packages/ui/src/assets/icon/Trophy.tsx
  packages/ui/src/assets/icon/index.ts
Labels: 🧑‍💻 feat

#104 feat : NavBar 퍼블리싱
  packages/ui/src/NavBar.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#109 fix : noImgIcon 불러오기 오류 수정
  packages/ui/src/assets/icon/index.ts
  packages/ui/src/assets/icon/noImgIcon.svg
Labels: 👾 BUG

#106 feat: 총 평가 자산 퍼블리싱
  packages/ui/src/TotalProperty.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#110 Feature/stock status bar
  packages/ui/src/ItemSidebar.tsx
  packages/ui/src/StockStatusBar.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#115 feat : stock graph 퍼블리싱
  packages/student/package.json
  packages/student/src/components/home/index.ts
  packages/student/src/components/home/stock/StockGraph.tsx
  packages/student/src/components/home/stock/index.ts
  packages/student/src/components/index.ts
  packages/student/src/layout/AppLayout.tsx
  packages/student/vite.config.ts
  yarn.lock
Labels: 🧑‍💻 feat

#112 feat : result container 퍼블리싱
  packages/student/src/components/index.ts
  packages/student/src/components/result/AssetChange.tsx
  packages/student/src/components/result/History.tsx
  packages/student/src/components/result/NthDeal.tsx
  packages/student/src/components/result/ResultContainer.tsx
  packages/student/src/components/result/index.ts
  packages/student/src/components/result/rank/RankModal.tsx
  packages/student/src/components/result/rank/index.ts
  packages/student/src/pages/test.tsx
  packages/ui/src/assets/icon/ArrowRight.tsx
  packages/ui/src/assets/icon/HandCoins.tsx
  packages/ui/src/assets/icon/index.ts
Labels: 🧑‍💻 feat

#116 매수 매도 모달 퍼블리싱
  packages/ui/src/BuySellModal.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat

#118 Feature/stock table
  packages/admin/src/components/monitoring/TeamInfoTable.tsx
  packages/ui/src/StockTable.tsx
  packages/ui/src/index.ts
Labels: 🧑‍💻 feat
