Repository team-mozu/mozu-FE, pull requests merged in 2025-02, with the labels that each got.

#124 feat : API 세팅, Toast ui 추가
  configs/util-config/package.json
  configs/util-config/src/constant/env.ts
  configs/util-config/src/constant/index.ts
  configs/util-config/src/index.ts
  configs/util-config/src/utils/apis/auth/index.ts
  configs/util-config/src/utils/apis/auth/types.ts
  configs/util-config/src/utils/apis/axios.ts
  configs/util-config/src/utils/apis/index.ts
  configs/util-config/src/utils/cookies.ts
  configs/util-config/src/utils/index.ts
  configs/util-config/tsconfig.json
  package.json
  packages/admin/package.json
  packages/admin/src/App.tsx
  packages/admin/src/index.tsx
  packages/admin/src/pages/index.ts
  packages/admin/src/router.tsx
  packages/admin/tsconfig.json
  packages/student/package.json
  packages/ui/package.json
  packages/ui/src/Toast.tsx
  packages/ui/src/ToastContainer.tsx
  packages/ui/src/assets/icon/Warning.tsx
  packages/ui/src/assets/icon/index.ts
  packages/ui/src/index.ts
  packages/ui/tsconfig.json
  yarn.lock
Labels: 🧑‍💻 feat, ⚙️ setting

#128 feat : 기사 api 연동
  packages/admin/src/apis/article/index.ts
  packages/admin/src/apis/article/type.ts
  packages/admin/src/apis/index.ts
  packages/admin/src/components/article/ImgContainer.tsx
  packages/admin/src/pages/ArticleManagementAddPage.tsx
  packages/admin/src/pages/ArticleManagementEditPage.tsx
  packages/admin/src/pages/ArticleManagementPage.tsx
  packages/admin/src/pages/ClassManagement.tsx
  packages/ui/src/EditDiv.tsx
Labels: 🧑‍💻 feat

#134 feat : [#131] 수업 api 연동
  .DS_Store
  .vscode/settings.json
  .yarn/sdks/eslint/bin/eslint.js
  .yarn/sdks/eslint/lib/api.js
  .yarn/sdks/eslint/lib/unsupported-api.js
  .yarn/sdks/prettier/bin/prettier.cjs
  .yarn/sdks/prettier/index.cjs
  .yarn/sdks/typescript/bin/tsc
  .yarn/sdks/typescript/bin/tsserver
  .yarn/sdks/typescript/lib/tsc.js
  .yarn/sdks/typescript/lib/tsserver.js
  .yarn/sdks/typescript/lib/tsserverlibrary.js
  .yarn/sdks/typescript/lib/typescript.js
  packages/admin/package.json
  packages/admin/src/apis/class/index.ts
  packages/admin/src/apis/class/type.ts
  packages/admin/src/apis/index.ts
  packages/admin/src/apis/login/adminLogin.tsx
  packages/admin/src/components/article/AddArticleItemModal.tsx
  packages/admin/src/components/article/ArticleItem.tsx
  packages/admin/src/components/common/ArticleTables.tsx
  packages/admin/src/components/common/StockTables.tsx
  packages/admin/src/components/common/Tables.tsx
  packages/admin/src/components/common/index.ts
  packages/admin/src/components/monitoring/TeamInfoTable.tsx
  packages/admin/src/components/monitoring/TeamInvestStatusTable.tsx
  packages/admin/src/hooks/index.ts
  packages/admin/src/hooks/usePriceFormatter.tsx
  packages/admin/src/pages/ClassCreate.tsx
  packages/admin/src/pages/ClassEdit.tsx
  packages/admin/src/pages/ClassEnvironment.tsx
  packages/admin/src/pages/ClassManagement.tsx
  packages/admin/src/store/index.ts
  packages/admin/src/store/type.ts
  packages/admin/src/store/useClassStore.tsx
  packages/admin/tsconfig.json
  packages/student/tsconfig.json
  packages/ui/src/Checkbox.tsx
  packages/ui/src/InvestInfoTable.tsx
  packages/ui/tsconfig.json
  yarn.lock
Labels: 🧑‍💻 feat, ♻️ refactor
